import type { ClassDef } from "../types";
import { add, card, note, replace } from "../_perkHelpers";

// Source: github.com/Lurkars/gloomhavensecretariat data/ccug/character/glacialtorrent.json
// Auto-generated by scripts/generate-fan-classes.ts. Custom-perk descriptions
// resolved against GHS's en labels where possible; ★ in card art means the
// effect is fan-expansion specific — see the perk description for the rule.

export const ccugGlacialTorrent: ClassDef = {
  id: "ccug-glacial-torrent",
  game: "ccug",
  name: "Glacial Torrent",
  iconRef: "glacialtorrent",
  rulesVariant: "fh",
  startingDeck: "base",
  perks: [
    replace("p01", 1, 1, card(-2), 1, card(-2, false, "brittle"), "Replace one -2 card with one -2 Brittle card"),
    replace("p02", 3, 1, card(-1), 1, card(0, false, "custom"), "Replace one -1 card with one +0 ★ card — 1"),
    replace("p03", 1, 2, card(0), 2, card(0, true, "push"), "Replace two +0 cards with two rolling +0 Push 2 cards"),
    replace("p04", 2, 1, card(0), 1, card(2, false, "custom"), "Replace one +0 card with one +2 ★ card — Create one 1-hex icy terrain tile in a featureless hex adjacent to the target"),
    add("p05", 2, 2, card(1, false, "ice"), "Add two +1 ICE cards"),
    add("p06", 1, 1, card(3), "Add one +3 card"),
    add("p07", 3, 1, card(0, true, "heal", "ward"), "Add one rolling +0 Heal 1 (Self) Ward (Self) card"),
    note("p08", 1, "Ignore item effects and, whenever you would gain Brittle, prevent the condition"),
    note("p09", 1, "Whenever one of your ally's heals would cause your hit point value to increase beyond your maximum hit point value, gain that much"),
    note("p10", 3, "Whenever you end your turn adjacent to icy terrain, perform Heal 1, self"),
  ],
};
