import type { ClassDef } from "../types";
import { add, card, multi, note, remove, replace } from "../_perkHelpers";

// Source: github.com/Lurkars/gloomhavensecretariat data/ccug/character/core.json
// Auto-generated by scripts/generate-fan-classes.ts. Custom-perk descriptions
// resolved against GHS's en labels where possible; ★ in card art means the
// effect is fan-expansion specific — see the perk description for the rule.

export const ccugCore: ClassDef = {
  id: "ccug-core",
  game: "ccug",
  name: "Core",
  iconRef: "core",
  rulesVariant: "gh",
  startingDeck: "base",
  perks: [
    replace("p01", 1, 1, card(-2), 1, card(0), "Replace one -2 card with one +0 card"),
    replace("p02", 2, 1, card(-1), 1, card(1, false, "wound"), "Replace one -1 card with one +1 Wound card — requires Wound (Self)"),
    replace("p03", 2, 1, card(-1), 1, card(1, false, "poison"), "Replace one -1 card with one +1 Poison Poison (Self) card"),
    replace("p04", 2, 1, card(0), 1, card(1, false, "immobilize"), "Replace one +0 card with one +1 Immobilize card"),
    add("p05", 2, 1, card(0, false, "custom"), "Add one +0 ★ card — Add for each condition you have"),
    add("p06", 2, 2, card(0, true, "heal"), "Add two rolling +0 Heal 1 cards"),
    add("p07", 2, 1, card(0, true, "ward", "regenerate"), "Add one rolling +0 Ward (Self) Regenerate (Self) card"),
    multi("p08", 1, "Add one -2 Brittle card and one +3 Brittle (Self) card", { op: "add", card: card(-2, false, "brittle"), count: 1 }, { op: "add", card: card(3, false, "brittle"), count: 1 }),
    remove("p09", 1, 1, card(0), "Remove one +0 card — Ignore item effects"),
    note("p10", 1, "At the start of each scenario you may perform \"Strengthen, Wound, Self\" or \"Ward, Immobilize, Self\""),
    note("p11", 1, "Once each scenario, avoid an Overdrive exhaustion check"),
    note("p12", 1, "Once each scenario, during your turn, remove any number of negative conditions you have"),
  ],
};
