import type { ClassDef } from "../types";
import { add, card, note, replace } from "../_perkHelpers";

// Source: github.com/Lurkars/gloomhavensecretariat data/ccug/character/veilpiercer.json
// Auto-generated by scripts/generate-fan-classes.ts. Custom-perk descriptions
// resolved against GHS's en labels where possible; ★ in card art means the
// effect is fan-expansion specific — see the perk description for the rule.

export const ccugVeilpiercer: ClassDef = {
  id: "ccug-veilpiercer",
  game: "ccug",
  name: "Veilpiercer",
  iconRef: "veilpiercer",
  rulesVariant: "gh",
  startingDeck: "base",
  perks: [
    replace("p01", 1, 1, card(-2), 1, card(0), "Replace one -2 card with one +0 card"),
    replace("p02", 3, 1, card(-1), 1, card(1), "Replace one -1 card with one +1 card"),
    replace("p03", 2, 1, card(0), 1, card(0, false, "custom"), "Replace one +0 card with one +0 ★ card — The target and all enemies adjacent to it suffer damage 1"),
    replace("p04", 2, 1, card(0), 1, card(0, true, "wound"), "Replace one +0 card with one rolling +0 Wound card"),
    add("p05", 2, 1, card(2, true, "pierce"), "Add one rolling +2 Pierce 2 card"),
    add("p06", 1, 1, card(0, true, "push", "immobilize"), "Add one rolling +0 Push 2 Immobilize card"),
    add("p07", 1, 2, card(0, true, "heal"), "Add two rolling +0 Heal 1 (Self) cards"),
    add("p08", 1, 2, card(0, true, "curse"), "Add two rolling +0 Curse cards"),
    add("p09", 1, 2, card(1), "Add two +1 cards — Ignore scenario effects"),
    note("p10", 1, "Unlock <b>The Astral Plane</b>, and start each scenario with Invisible"),
    note("p11", 1, "Whenever you long rest, you may perform \"Teleport 2\""),
    note("p12", 2, "Once each scenario, during your turn, place one in a hex within Range 4"),
  ],
};
