import type { ClassDef } from "../types";
import { add, card, multi, note, remove, replace } from "../_perkHelpers";

// Source: github.com/Lurkars/gloomhavensecretariat data/ccug/character/alchemancer.json
// Auto-generated by scripts/generate-fan-classes.ts. Custom-perk descriptions
// resolved against GHS's en labels where possible; ★ in card art means the
// effect is fan-expansion specific — see the perk description for the rule.

export const ccugAlchemancer: ClassDef = {
  id: "ccug-alchemancer",
  game: "ccug",
  name: "Alchemancer",
  iconRef: "alchemancer",
  rulesVariant: "gh",
  startingDeck: "base",
  perks: [
    replace("p01", 1, 1, card(-2), 1, card(-1, false, "custom"), "Replace one -2 card with one -1 ★ card — consume WILD"),
    replace("p02", 3, 1, card(-1), 1, card(0, false, "wild"), "Replace one -1 card with one +0 WILD card"),
    replace("p03", 3, 1, card(0), 1, card(0, false, "custom"), "Replace one +0 card with one +0 ★ card — Add a to an active"),
    replace("p04", 2, 1, card(0), 1, card(1, false, "immobilize"), "Replace one +0 card with one +1 Immobilize card"),
    add("p05", 2, 2, card(1, false, "custom"), "Add two +1 ★ cards — If you drew this as part of a ability, instead"),
    multi("p06", 2, "Add one rolling +0 FIRE/ICE (half-element) card and one rolling +0 FIRE/EARTH (half-element) card and one rolling +0 ICE/EARTH (half-element) card", { op: "add", card: card(0, true, "fire", "ice"), count: 1 }, { op: "add", card: card(0, true, "fire", "earth"), count: 1 }, { op: "add", card: card(0, true, "ice", "earth"), count: 1 }),
    remove("p07", 1, 1, card(0), "Remove one +0 card — Ignore scenario effects"),
    note("p08", 1, "Whenever you rest, you may: Wild"),
    note("p09", 1, "Whenever you consume a potion, you may place one on an active card"),
    note("p10", 2, "At the end of each of your turns during which you performed no attacks and you are not perfoming a long rest, Fire, Ice, or Earth"),
  ],
};
