import type { ClassDef } from "../types";
import { add, card, note, replace } from "../_perkHelpers";

// Source: github.com/Lurkars/gloomhavensecretariat data/ccug/character/echowight.json
// Auto-generated by scripts/generate-fan-classes.ts. Custom-perk descriptions
// resolved against GHS's en labels where possible; ★ in card art means the
// effect is fan-expansion specific — see the perk description for the rule.

export const ccugEchowight: ClassDef = {
  id: "ccug-echowight",
  game: "ccug",
  name: "Echowight",
  iconRef: "echowight",
  rulesVariant: "gh",
  startingDeck: "base",
  perks: [
    replace("p01", 1, 1, card(-2), 1, card(0), "Replace one -2 card with one +0 card"),
    replace("p02", 3, 1, card(-1), 1, card(0, false, "custom"), "Replace one -1 card with one +0 ★ card — One enemy adjacent to suffers damage 1"),
    replace("p03", 2, 1, card(0), 1, card(1, false, "curse"), "Replace one +0 card with one +1 Curse card"),
    replace("p04", 2, 1, card(0), 1, card(1, false, "air"), "Replace one +0 card with one +1 AIR card"),
    add("p05", 1, 1, card(1, false, "custom"), "Add one +1 ★ card — for each adjacent to the target"),
    add("p06", 2, 1, card(2, false, "custom"), "Add one +2 ★ card — Place one in a hex adjacent to the target"),
    add("p07", 2, 2, card(0, true, "heal"), "Add two rolling +0 Heal 1 (Target 1 figure adjacent to) cards"),
    add("p08", 1, 2, card(1), "Add two +1 cards — Ignore scenario effects"),
    note("p09", 2, "At the end of your turn, if you are adjacent to and have not moved this turn, you may perform: Move 1"),
    note("p10", 1, "Once per round, when a door is opened, you may relocate a to a hex within Range 1 of the opened door"),
    note("p11", 1, "Enemies gain for each adjacent"),
  ],
};
