import type { ClassDef } from "../types";
import { add, card, multi, note, replace } from "../_perkHelpers";

// Source: github.com/Lurkars/gloomhavensecretariat data/ccug/character/lightracer.json
// Auto-generated by scripts/generate-fan-classes.ts. Custom-perk descriptions
// resolved against GHS's en labels where possible; ★ in card art means the
// effect is fan-expansion specific — see the perk description for the rule.

export const ccugLightracer: ClassDef = {
  id: "ccug-lightracer",
  game: "ccug",
  name: "Lightracer",
  iconRef: "lightracer",
  rulesVariant: "gh",
  startingDeck: "base",
  perks: [
    replace("p01", 1, 1, card(-2), 1, card(-1, false, "bless"), "Replace one -2 card with one -1 Bless (Self) card"),
    replace("p02", 1, 1, card(-1), 1, card(0, false, "immobilize"), "Replace one -1 card with one +0 Immobilize card"),
    replace("p03", 2, 1, card(-1), 1, card(0, false, "heal"), "Replace one -1 card with one +0 Heal 1 (Self) card"),
    replace("p04", 3, 1, card(0), 1, card(1, false, "push", "custom"), "Replace one +0 card with one +1 Push 1 ★ card"),
    replace("p05", 3, 1, card(0), 1, card(1, false, "custom"), "Replace one +0 card with one +1 ★ card — You may discard a Speed card to add and Muddle"),
    add("p06", 2, 1, card(1, false, "disarm"), "Add one +1 Disarm card"),
    multi("p07", 2, "Add one rolling +0 Ward (range 3) card and one rolling +0 Bless (range 3) card", { op: "add", card: card(0, true, "ward"), count: 1 }, { op: "add", card: card(0, true, "bless"), count: 1 }),
    note("p08", 1, "Ignore scenario effects and when you suffer damage during your turn, you may ignore Ward"),
    note("p09", 2, "Whenever you draw a Bless, perform Ward Target 1 ally. If that ally already had Ward, Heal 1 that ally"),
    note("p10", 1, "Once each scenario, you may use all of your played cards for their standard action and ignore damage from Speeds that turn"),
  ],
};
