import type { ClassDef } from "../types";
import { add, card, note, replace } from "../_perkHelpers";

// Source: github.com/Lurkars/gloomhavensecretariat data/ccug/character/rekindled.json
// Auto-generated by scripts/generate-fan-classes.ts. Custom-perk descriptions
// resolved against GHS's en labels where possible; ★ in card art means the
// effect is fan-expansion specific — see the perk description for the rule.

export const ccugRekindled: ClassDef = {
  id: "ccug-rekindled",
  game: "ccug",
  name: "Rekindled",
  iconRef: "rekindled",
  rulesVariant: "gh",
  startingDeck: "base",
  perks: [
    replace("p01", 1, 1, card(-2), 1, card(0), "Replace one -2 card with one +0 card"),
    replace("p02", 2, 1, card(-1), 1, card(-1, true, "custom"), "Replace one -1 card with one rolling -1 ★ card — Grant one ally: Attack 2"),
    replace("p03", 2, 1, card(-1), 1, card(0, false, "fire"), "Replace one -1 card with one +0 FIRE card"),
    replace("p04", 3, 1, card(0), 1, card(1, false, "custom"), "Replace one +0 card with one +1 ★ card — Add if you have two or more in your active area"),
    replace("p05", 2, 1, card(0), 1, card(1, false, "disarm"), "Replace one +0 card with one +1 Disarm card"),
    add("p06", 2, 2, card(1, false, "custom"), "Add two +1 ★ cards — Place a in a hex adjacent to or occupied by the target of the attack"),
    add("p07", 1, 1, card(0, true, "bless"), "Add one rolling +0 Bless (Ally) card — Ignore scenario effects"),
    note("p08", 1, "Whenever you rest, perform: Strengthen, Target 1 ally within Range 2 of a"),
    note("p09", 2, "On your first turn each scenario, you may play three cards instead of two"),
    note("p10", 2, "Once per scenario, when you would suffer damage, you may Teleport to an unoccupied to negate the damage"),
  ],
};
