import type { ClassDef } from "../types";
import { add, card, note, remove, replace } from "../_perkHelpers";

// Source: github.com/Lurkars/gloomhavensecretariat data/ccug/character/wildborn.json
// Auto-generated by scripts/generate-fan-classes.ts. Custom-perk descriptions
// resolved against GHS's en labels where possible; ★ in card art means the
// effect is fan-expansion specific — see the perk description for the rule.

export const ccugWildborn: ClassDef = {
  id: "ccug-wildborn",
  game: "ccug",
  name: "Wildborn",
  iconRef: "wildborn",
  rulesVariant: "gh",
  startingDeck: "base",
  perks: [
    replace("p01", 1, 1, card(-2), 1, card(-1, false, "custom"), "Replace one -2 card with one -1 ★ card — transforms to instead if you suffer damage 2"),
    replace("p02", 2, 2, card(-1), 1, card(-1, false, "poison"), "Replace two -1 cards with one -1 Poison card"),
    replace("p03", 2, 2, card(0), 1, card(1, false, "pierce"), "Replace two +0 cards with one +1 Pierce 3 card"),
    replace("p04", 2, 2, card(1), 2, card(2), "Replace two +1 cards with two +2 cards"),
    add("p05", 2, 1, card(2, false, "ward"), "Add one +2 Ward (Self) card"),
    add("p06", 1, 1, card(0, false, "custom"), "Add one +0 ★ card — Add per collected"),
    add("p07", 2, 1, card(0, true, "heal"), "Add one rolling +0 Heal 1 card"),
    add("p08", 3, 1, card(1, false, "custom"), "Add one +1 ★ card — Place this card in your active area. On your next commanded attack, discard this card to add"),
    note("p09", 1, "Ignore negative scenario effects and treat all as Stable during one round each scenario"),
    remove("p10", 1, 1, card(0), "Remove one +0 card — Whenever you or one of your allies would suffer exactly damage 2, that figure may lose Ward to suffer no damage instead"),
    note("p11", 1, "At the start of each scenario, you may Wild"),
  ],
};
