import type { ClassDef } from "../types";
import { add, card, multi, note, remove, replace } from "../_perkHelpers";

// Source: github.com/Lurkars/gloomhavensecretariat data/ccug/character/lifespeaker.json
// Auto-generated by scripts/generate-fan-classes.ts. Custom-perk descriptions
// resolved against GHS's en labels where possible; ★ in card art means the
// effect is fan-expansion specific — see the perk description for the rule.

export const ccugLifespeaker: ClassDef = {
  id: "ccug-lifespeaker",
  game: "ccug",
  name: "Lifespeaker",
  iconRef: "lifespeaker",
  rulesVariant: "gh",
  startingDeck: "base",
  perks: [
    remove("p01", 1, 1, card(-2), "Remove one -2 card"),
    replace("p02", 3, 1, card(-1), 1, card(0, false, "custom"), "Replace one -1 card with one +0 Enfeeble card"),
    multi("p03", 3, "Replace one +0 card with one +1 card and one +1 Pierce 1 Push 1 Regenerate (range 2) card", { op: "remove", card: card(0), count: 1 }, { op: "add", card: card(1), count: 1 }, { op: "add", card: card(1, false, "pierce", "push", "regenerate"), count: 1 }),
    add("p04", 3, 1, card(0, true, "custom"), "Add one rolling +0 ★ card — Place this card in your active area. The next time you trigger an element consumption effect, discard this card to gain the effect an additional time"),
    add("p05", 3, 1, card(1, true, "custom"), "Add one rolling +1 ★ card — Add and suffer damage 1 if has at least 2"),
    note("p06", 1, "Ignore scenario effects, and, at the start of each of your turns, any number of times, perform: -1: Move the character token on one of your persistent abilities backwards one slot."),
    note("p07", 1, "Once each scenario, you may gain up to three Enfeeble cards to gain the same number of"),
    note("p08", 3, "Whenever an enemy draws an Enfeeble card, that enemy reduces the value of their attack by 1 and suffers damage 1 after the attack."),
  ],
};
