import type { ClassDef } from "../types";
import { add, card, note, replace } from "../_perkHelpers";

// Source: github.com/Lurkars/gloomhavensecretariat data/ccug/character/jestertwins.json
// Auto-generated by scripts/generate-fan-classes.ts. Custom-perk descriptions
// resolved against GHS's en labels where possible; ★ in card art means the
// effect is fan-expansion specific — see the perk description for the rule.

export const ccugJesterTwins: ClassDef = {
  id: "ccug-jester-twins",
  game: "ccug",
  name: "Jester Twins",
  iconRef: "jestertwins",
  rulesVariant: "gh",
  startingDeck: "base",
  perks: [
    replace("p01", 3, 1, card(-1), 1, card(1), "Replace one -1 card with one +1 card"),
    replace("p02", 2, 1, card(-1), 1, card(0, false, "poison"), "Replace one -1 card with one +0 Poison card"),
    replace("p03", 2, 1, card(0), 1, card(1, false, "immobilize"), "Replace one +0 card with one +1 Immobilize card"),
    replace("p04", 3, 1, card(1), 1, card(2, false, "swing"), "Replace one +1 card with one +2 Swing 3 card"),
    add("p05", 2, 1, card(0, true, "custom"), "Add one rolling +0 ★ card — Place this card in your active area. The next time you force an enemy to move, discard this card and that enemy suffers damage 2"),
    add("p06", 1, 1, card(2, false, "custom"), "Add one +2 ★ card — If you are not after this attack ability, Teleport the other to your hex and become"),
    add("p07", 1, 2, card(0, true, "swing"), "Add two rolling +0 Swing 2 cards — Ignore scenario effects"),
    note("p08", 2, "If you are not, you may end your movement in a hex occupied by an ally to become on top of the ally"),
    note("p09", 2, "You may bring one additional item into each scenario"),
    note("p10", 1, "Your forced movement can move allies through enemies, and enemies through allies"),
  ],
};
