import type { ClassDef } from "../types";
import { add, card, multi, note, replace } from "../_perkHelpers";

// Source: github.com/Lurkars/gloomhavensecretariat data/ccug/character/woebound.json
// Auto-generated by scripts/generate-fan-classes.ts. Custom-perk descriptions
// resolved against GHS's en labels where possible; ★ in card art means the
// effect is fan-expansion specific — see the perk description for the rule.

export const ccugWoebound: ClassDef = {
  id: "ccug-woebound",
  game: "ccug",
  name: "Woebound",
  iconRef: "woebound",
  rulesVariant: "fh",
  startingDeck: "base",
  perks: [
    replace("p01", 1, 1, card(-2), 1, card(-4, false, "custom"), "Replace one -2 card with one -4 ★ card — consume WILD: Bane"),
    multi("p02", 2, "Replace one -1 card with one rolling +0 ICE card and one rolling +0 AIR card", { op: "remove", card: card(-1), count: 1 }, { op: "add", card: card(0, true, "ice"), count: 1 }, { op: "add", card: card(0, true, "air"), count: 1 }),
    replace("p03", 2, 1, card(-1), 1, card(0, true, "pierce"), "Replace one -1 card with one rolling +0 Pierce 2 card — requires FIRE, ICE"),
    replace("p04", 2, 1, card(0), 1, card(2), "Replace one +0 card with one +2 card — requires LIGHT, DARK"),
    multi("p05", 2, "Replace two +0 cards with one +1 DARK card and one +1 FIRE card", { op: "remove", card: card(0), count: 2 }, { op: "add", card: card(1, false, "dark"), count: 1 }, { op: "add", card: card(1, false, "fire"), count: 1 }),
    add("p06", 2, 1, card(1, false, "disarm"), "Add one +1 Disarm card — requires AIR, EARTH"),
    multi("p07", 2, "Add one rolling +0 Heal 1 (Self) LIGHT card and one rolling +0 Heal 1 (Self) EARTH card", { op: "add", card: card(0, true, "heal", "light"), count: 1 }, { op: "add", card: card(0, true, "heal", "earth"), count: 1 }),
    add("p08", 2, 1, card(0, false, "custom"), "Add one +X ★ card — where X is the number elements you have consumed this turn"),
    note("p09", 1, "Whenever you consume an element as a mandatory part of an action, you may generate that same element"),
    note("p10", 1, "At the start of each scenario, Wild"),
    note("p11", 1, "Whenever you long rest, Wild"),
  ],
};
