import type { ClassDef } from "../types";
import { add, card, note, replace } from "../_perkHelpers";

// Source: github.com/Lurkars/gloomhavensecretariat data/ccug/character/skitterclaw.json
// Auto-generated by scripts/generate-fan-classes.ts. Custom-perk descriptions
// resolved against GHS's en labels where possible; ★ in card art means the
// effect is fan-expansion specific — see the perk description for the rule.

export const ccugSkitterclaw: ClassDef = {
  id: "ccug-skitterclaw",
  game: "ccug",
  name: "Skitterclaw",
  iconRef: "skitterclaw",
  rulesVariant: "gh",
  startingDeck: "base",
  perks: [
    replace("p01", 1, 1, card(-2), 1, card(0), "Replace one -2 card with one +0 card"),
    replace("p02", 2, 1, card(-1), 1, card(0, false, "immobilize"), "Replace one -1 card with one +0 Immobilize card"),
    replace("p03", 3, 1, card(-1), 1, card(0, false, "custom"), "Replace one -1 card with one +0 ★ card — After the attack ability, grant one of your summons: Move 2"),
    replace("p04", 2, 1, card(0), 1, card(1, false, "custom"), "Replace one +0 card with one +1 ★ card — If the target is Latched, instead"),
    replace("p05", 1, 1, card(0), 1, card(1, false, "poison"), "Replace one +0 card with one +1 Poison card"),
    add("p06", 1, 2, card(0, true, "heal"), "Add two rolling +0 Heal 1 (Ally) cards"),
    add("p07", 2, 1, card(1, false, "custom"), "Add one +1 ★ card — All Latched enemies suffer damage 1"),
    add("p08", 1, 1, card(1), "Add one +1 card — Ignore scenario effects"),
    note("p09", 1, "You may summon summons in adjacent occupied hexes"),
    note("p10", 2, "Once per scenario, when you or an ally would suffer damage from an attack, remove a Latched summon from the attacker or the target to negate the damage instead"),
    note("p11", 2, "At the start of each scenario, you may play a card from your hand to perform a summon action of the card"),
  ],
};
