import type { ClassDef } from "../types";
import { add, card, note, remove, replace } from "../_perkHelpers";

// Source: github.com/Lurkars/gloomhavensecretariat data/ccug/character/rootwhisperer.json
// Auto-generated by scripts/generate-fan-classes.ts. Custom-perk descriptions
// resolved against GHS's en labels where possible; ★ in card art means the
// effect is fan-expansion specific — see the perk description for the rule.

export const ccugRootwhisperer: ClassDef = {
  id: "ccug-rootwhisperer",
  game: "ccug",
  name: "Rootwhisperer",
  iconRef: "rootwhisperer",
  rulesVariant: "gh",
  startingDeck: "base",
  perks: [
    remove("p01", 2, 2, card(-1), "Remove two -1 cards"),
    remove("p02", 1, 4, card(0), "Remove four +0 cards"),
    replace("p03", 2, 1, card(0), 1, card(2), "Replace one +0 card with one +2 card"),
    add("p04", 2, 1, card(2, true), "Add one rolling +2 card"),
    add("p05", 2, 1, card(1, false, "immobilize"), "Add one +1 Immobilize card"),
    add("p06", 2, 2, card(0, true, "poison"), "Add two rolling +0 Poison cards"),
    add("p07", 1, 1, card(0, true, "disarm"), "Add one rolling +0 Disarm card"),
    add("p08", 2, 1, card(0, true, "heal", "earth"), "Add one rolling +0 Heal 2 EARTH card"),
    note("p09", 1, "Ignore scenario effects"),
  ],
};
