import type { ClassDef } from "../types";
import { add, card, note, remove, replace } from "../_perkHelpers";

// Source: github.com/Lurkars/gloomhavensecretariat data/ccug/character/frostborn.json
// Auto-generated by scripts/generate-fan-classes.ts. Custom-perk descriptions
// resolved against GHS's en labels where possible; ★ in card art means the
// effect is fan-expansion specific — see the perk description for the rule.

export const ccugFrostborn: ClassDef = {
  id: "ccug-frostborn",
  game: "ccug",
  name: "Frostborn",
  iconRef: "frostborn",
  rulesVariant: "fh",
  startingDeck: "base",
  perks: [
    remove("p01", 2, 2, card(-1), "Remove two -1 cards"),
    replace("p02", 1, 1, card(-2), 1, card(0, false, "chill"), "Replace one -2 card with one +0 Chill card"),
    replace("p03", 2, 2, card(0), 2, card(1, false, "push"), "Replace two +0 cards with two +1 Push 1 cards"),
    replace("p04", 2, 1, card(0), 1, card(1, false, "ice", "chill"), "Replace one +0 card with one +1 ICE Chill card"),
    replace("p05", 1, 1, card(1), 1, card(3), "Replace one +1 card with one +3 card"),
    add("p06", 1, 1, card(0, false, "stun"), "Add one +0 Stun card"),
    add("p07", 2, 1, card(0, true, "target"), "Add one rolling +0 Target 1 card"),
    add("p08", 1, 3, card(0, true, "chill"), "Add three rolling +0 Chill cards"),
    add("p09", 1, 3, card(0, true, "push"), "Add three rolling +0 Push 1 cards"),
    note("p10", 1, "Ignore difficult and hazardous terrain during move actions"),
    note("p11", 1, "Ignore scenario effects"),
  ],
};
