import type { ClassDef } from "../types";
import { add, card, note, replace } from "../_perkHelpers";

// Source: github.com/Lurkars/gloomhavensecretariat data/ccug/character/progenitor.json
// Auto-generated by scripts/generate-fan-classes.ts. Custom-perk descriptions
// resolved against GHS's en labels where possible; ★ in card art means the
// effect is fan-expansion specific — see the perk description for the rule.

export const ccugProgenitor: ClassDef = {
  id: "ccug-progenitor",
  game: "ccug",
  name: "Progenitor",
  iconRef: "progenitor",
  rulesVariant: "fh",
  startingDeck: "base",
  perks: [
    replace("p01", 1, 1, card(-2), 1, card(-2, false, "muddle", "custom"), "Replace one -2 card with one -2 Muddle ★ card — Add Stun and Wound if this attack is Ponderous"),
    replace("p02", 1, 2, card(-1), 2, card(-1, false, "push", "custom"), "Replace two -1 cards with two -1 Push 1 ★ cards — Add instead if this attack is Ponderous"),
    replace("p03", 3, 1, card(-1), 1, card(0, true, "pierce", "muddle"), "Replace one -1 card with one rolling +0 Pierce 3 Muddle card"),
    replace("p04", 2, 1, card(1), 1, card(2, false, "regenerate"), "Replace one +1 card with one +2 Regenerate (Self) card"),
    replace("p05", 1, 1, card(0), 1, card(0, false, "strengthen"), "Replace one +0 card with one +0 Strengthen (Self) card"),
    add("p06", 2, 1, card(3), "Add one +3 card"),
    add("p07", 2, 1, card(1, true, "heal"), "Add one rolling +1 Heal 1 (Self) card"),
    add("p08", 2, 1, card(0, true, "custom"), "Add one rolling +0 ★ card — Place this card in your active area. Shield 1. At the start of your next turn, discard this card and Move 1"),
    note("p09", 2, "Ignore item effects. You are considered to be first in initiative order to determine focus while Ancient Carapace is not spent"),
    note("p10", 1, "Once each scenario, perform the Ponderous abilities of a card as you play it"),
    note("p11", 1, "Ignore the effects of Immobilize, Disarm, Impair, Stun, and Muddle during the start of your turn"),
  ],
};
