import type { ClassDef } from "../types";
import { add, card, note, replace } from "../_perkHelpers";

// Source: github.com/Lurkars/gloomhavensecretariat data/ccug/character/swarmshift.json
// Auto-generated by scripts/generate-fan-classes.ts. Custom-perk descriptions
// resolved against GHS's en labels where possible; ★ in card art means the
// effect is fan-expansion specific — see the perk description for the rule.

export const ccugSwarmshift: ClassDef = {
  id: "ccug-swarmshift",
  game: "ccug",
  name: "Swarmshift",
  iconRef: "swarmshift",
  rulesVariant: "gh",
  startingDeck: "base",
  perks: [
    replace("p01", 2, 1, card(-1), 1, card(1), "Replace one -1 card with one +1 card"),
    replace("p02", 2, 1, card(-1), 1, card(0, true, "shield"), "Replace one -1 card with one rolling +0 Shield 1 card"),
    replace("p03", 2, 1, card(0), 1, card(1, false, "custom"), "Replace one +0 card with one +1 ★ card — Add for each active Hivecall"),
    replace("p04", 2, 1, card(0), 1, card(1, false, "immobilize"), "Replace one +0 card with one +1 Immobilize card"),
    add("p05", 2, 2, card(0, true, "heal"), "Add two rolling +0 Heal 1 (Self) cards"),
    add("p06", 2, 1, card(1, false, "custom"), "Add one +1 ★ card — Gain 1"),
    add("p07", 2, 1, card(2, false, "earth"), "Add one +2 EARTH card"),
    add("p08", 1, 1, card(1), "Add one +1 card — Ignore item effects"),
    note("p09", 1, "Whenever you complete a long rest, you may gain Poison to gain 1."),
    note("p10", 1, "Whenever you short rest, you may -1 to Recover two of your spent items."),
    note("p11", 1, "Whenever you spend 2 or more in a turn, you may Earth."),
  ],
};
