import type { ClassDef } from "../types";
import { add, card, note, replace } from "../_perkHelpers";

// Source: github.com/Lurkars/gloomhavensecretariat data/ccug/character/reeftender.json
// Auto-generated by scripts/generate-fan-classes.ts. Custom-perk descriptions
// resolved against GHS's en labels where possible; ★ in card art means the
// effect is fan-expansion specific — see the perk description for the rule.

export const ccugReeftender: ClassDef = {
  id: "ccug-reeftender",
  game: "ccug",
  name: "Reeftender",
  iconRef: "reeftender",
  rulesVariant: "gh",
  startingDeck: "base",
  perks: [
    replace("p01", 1, 1, card(-2), 1, card(0), "Replace one -2 card with one +0 card"),
    replace("p02", 3, 1, card(-1), 1, card(0, false, "heal"), "Replace one -1 card with one +0 Heal 1 card"),
    replace("p03", 2, 1, card(0), 1, card(1, false, "ward"), "Replace one +0 card with one +1 Ward (range 3) card"),
    replace("p04", 2, 1, card(0), 1, card(1, false, "custom"), "Replace one +0 card with one +1 ★ card — After this attack ability, Teleport one of your summons to an unoccupied hex adjacent to"),
    add("p05", 2, 1, card(1, true, "poison"), "Add one rolling +1 Poison card"),
    add("p06", 2, 1, card(2, false, "earth", "light"), "Add one +2 EARTH/LIGHT (half-element) card"),
    add("p07", 1, 1, card(1), "Add one +1 card — Ignore item effects"),
    note("p08", 1, "Whenever you declare a long rest, you may move one of your summons to your discard pile to perform Ward, self"),
    note("p09", 1, "Once each scenario, when your summon would suffer damage, negate the damage, Teleport to the hex occupied by that summon, and place that summon in an empty hex closest to you"),
    note("p10", 3, "Your summons gain advantage on all attacks performed while adjacent to you"),
  ],
};
