import type { ClassDef } from "../types";
import { add, card, note, replace } from "../_perkHelpers";

// Source: github.com/Lurkars/gloomhavensecretariat data/ccug/character/powdercoat.json
// Auto-generated by scripts/generate-fan-classes.ts. Custom-perk descriptions
// resolved against GHS's en labels where possible; ★ in card art means the
// effect is fan-expansion specific — see the perk description for the rule.

export const ccugPowdercoat: ClassDef = {
  id: "ccug-powdercoat",
  game: "ccug",
  name: "Powdercoat",
  iconRef: "powdercoat",
  rulesVariant: "gh",
  startingDeck: "base",
  perks: [
    replace("p01", 1, 1, card(-2), 1, card(0), "Replace one -2 card with one +0 card"),
    replace("p02", 3, 1, card(-1), 1, card(1), "Replace one -1 card with one +1 card"),
    replace("p03", 2, 1, card(0), 1, card(1, false, "custom"), "Replace one +0 card with one +1 ★ card — Add if drawn during a ability"),
    replace("p04", 2, 1, card(0), 1, card(1, false, "custom"), "Replace one +0 card with one +1 ★ card"),
    add("p05", 2, 1, card(2, false, "fire"), "Add one +2 FIRE card"),
    add("p06", 2, 1, card(1, true, "custom"), "Add one rolling +1 ★ card — All enemies adjacent to the target suffer damage 1."),
    add("p07", 1, 2, card(1, false, "heal"), "Add two +1 Heal 1 (Ally) cards"),
    add("p08", 1, 1, card(1, true), "Add one rolling +1 card — Ignore scenario effects"),
    note("p09", 1, "You may place in hexes containing difficult terrain"),
    note("p10", 1, "Whenever one of your allies destroys a, that figure may perform Heal 2, self"),
    note("p11", 2, "Once each scenario, when you place or relocate a you may destroy it"),
  ],
};
