import type { ClassDef } from "../types";
import { add, card, note, replace } from "../_perkHelpers";

// Source: github.com/Lurkars/gloomhavensecretariat data/ccug/character/dome.json
// Auto-generated by scripts/generate-fan-classes.ts. Custom-perk descriptions
// resolved against GHS's en labels where possible; ★ in card art means the
// effect is fan-expansion specific — see the perk description for the rule.

export const ccugDome: ClassDef = {
  id: "ccug-dome",
  game: "ccug",
  name: "Dome",
  iconRef: "dome",
  rulesVariant: "gh",
  startingDeck: "base",
  perks: [
    replace("p01", 2, 1, card(-1), 1, card(0, true, "strengthen"), "Replace one -1 card with one rolling +0 Strengthen (Ally) card"),
    replace("p02", 2, 1, card(-1), 1, card(0, false, "custom"), "Replace one -1 card with one +0 ★ card — Grant the ally with: Attack 2"),
    replace("p03", 2, 1, card(0), 1, card(0, false, "custom"), "Replace one +0 card with one +0 ★ card — Place this card in your active area. On your next attack granting ability, discard this card to add"),
    replace("p04", 1, 2, card(0), 2, card(0, true, "pierce"), "Replace two +0 cards with two rolling +0 Pierce 3 cards"),
    add("p05", 2, 3, card(0, true, "custom"), "Add three rolling +0 ★ cards — 1"),
    add("p06", 2, 1, card(2, false, "light"), "Add one +2 LIGHT card"),
    replace("p07", 2, 1, card(0), 1, card(1, true, "regenerate"), "Replace one +0 card with one rolling +1 Regenerate (Self) card"),
    note("p08", 2, "Your summons gain Retaliate 1. Whenever one of your summons dies, perform: 3"),
    note("p09", 1, "At the end of each of your rests, perform: 1 and Range 4"),
    note("p10", 2, "Once each scenario, at the end of an ally's turn, perform: 5 and, Target that ally"),
  ],
};
