import type { ClassDef } from "../types";
import { add, card, note, remove, replace } from "../_perkHelpers";

// Source: github.com/Lurkars/gloomhavensecretariat data/ccug/character/vimthreader.json
// Auto-generated by scripts/generate-fan-classes.ts. Custom-perk descriptions
// resolved against GHS's en labels where possible; ★ in card art means the
// effect is fan-expansion specific — see the perk description for the rule.

export const ccugVimthreader: ClassDef = {
  id: "ccug-vimthreader",
  game: "ccug",
  name: "Vimthreader",
  iconRef: "vimthreader",
  rulesVariant: "gh",
  startingDeck: "base",
  perks: [
    replace("p01", 1, 1, card(-2), 1, card(-1, false, "custom"), "Replace one -2 card with one -1 ★ card — If the target has an attribute, add Wound, Poison, Muddle"),
    replace("p02", 2, 1, card(-1), 1, card(0, false, "custom"), "Replace one -1 card with one +0 Enfeeble card"),
    replace("p03", 2, 1, card(-1), 1, card(0, false, "custom"), "Replace one -1 card with one +0 Empower (range 2) card"),
    replace("p04", 3, 1, card(0), 1, card(1, false, "heal"), "Replace one +0 card with one +1 Heal 1 (Ally) card"),
    replace("p05", 1, 1, card(2), 4, card(1, true), "Replace one +2 card with four rolling +1 cards"),
    add("p06", 1, 2, card(0, true, "pierce", "poison"), "Add two rolling +0 Pierce 2 Poison cards"),
    add("p07", 2, 3, card(0, true, "heal"), "Add three rolling +0 Heal 1 cards"),
    remove("p08", 1, 1, card(0), "Remove one +0 card — Ignore scenario effects"),
    remove("p09", 1, 1, card(0), "Remove one +0 card — Ignore item effects"),
    note("p10", 1, "Whenever you short rest, one adjacent enemy suffers damage 1, and you perform \"Heal 1, self\""),
    note("p11", 2, "At the start of each scenario, you may suffer damage 1 to grant all allies and self Move 3"),
    note("p12", 1, "Once each scenario, remove all negative conditions you have. One adjacent enemy suffers damage equal to the number of conditions removed"),
  ],
};
