import type { ClassDef } from "../types";
import { add, card, multi, replace } from "../_perkHelpers";

// Source: github.com/Lurkars/gloomhavensecretariat data/cs/character/vortex.json
// Auto-generated by scripts/generate-fan-classes.ts. Custom-perk descriptions
// resolved against GHS's en labels where possible; ★ in card art means the
// effect is fan-expansion specific — see the perk description for the rule.

export const csArtificer: ClassDef = {
  id: "cs-artificer",
  game: "crimson-scales",
  name: "Artificer",
  codeName: "Vortex",
  iconRef: "vortex",
  rulesVariant: "gh",
  startingDeck: "base",
  perks: [
    replace("p01", 2, 1, card(-1), 1, card(0, false, "heal"), "Replace one -1 card with one +0 Heal 2 (Self) card"),
    replace("p02", 2, 2, card(0), 1, card(0, false, "custom"), "Replace two +0 cards with one +0 ★ card — Voidsight"),
    multi("p03", 2, "Add one -2 EARTH card and two +2 DARK cards", { op: "add", card: card(-2, false, "earth"), count: 1 }, { op: "add", card: card(2, false, "dark"), count: 2 }),
    multi("p04", 1, "Replace one -1 card with one -2 Stun card and one +0 ★ card — Voidsight", { op: "remove", card: card(-1), count: 1 }, { op: "add", card: card(-2, false, "stun"), count: 1 }, { op: "add", card: card(0, false, "custom"), count: 1 }),
    multi("p05", 1, "Replace one -2 card with one +0 Disarm card and one -1 WILD card", { op: "remove", card: card(-2), count: 1 }, { op: "add", card: card(0, false, "disarm"), count: 1 }, { op: "add", card: card(-1, false, "wild"), count: 1 }),
    multi("p06", 2, "Replace one -1 card with one rolling +1 ★ card and one rolling -1 Curse card", { op: "remove", card: card(-1), count: 1 }, { op: "add", card: card(1, true, "custom"), count: 1 }, { op: "add", card: card(-1, true, "curse"), count: 1 }),
    replace("p07", 2, 2, card(1), 2, card(3, false, "regenerate"), "Replace two +1 cards with two +3 Regenerate (Self) cards"),
    replace("p08", 2, 1, card(0), 1, card(1, false, "custom"), "Replace one +0 card with one +1 ★ card — Create a Void pit in an empty hex within Range 2"),
    add("p09", 1, 1, card(0, false, "ward"), "Add one +0 Ward (Self) card — Ignore negative scenario effects"),
  ],
};
