import type { ClassDef } from "../types";
import { add, card, note, remove, replace } from "../_perkHelpers";

// Source: github.com/Lurkars/gloomhavensecretariat data/cs/character/sprig.json
// Auto-generated by scripts/generate-fan-classes.ts. Custom-perk descriptions
// resolved against GHS's en labels where possible; ★ in card art means the
// effect is fan-expansion specific — see the perk description for the rule.

export const csAmberAegis: ClassDef = {
  id: "cs-amber-aegis",
  game: "crimson-scales",
  name: "Amber Aegis",
  codeName: "Sprig",
  iconRef: "sprig",
  rulesVariant: "gh",
  startingDeck: "base",
  perks: [
    replace("p01", 1, 1, card(-2), 1, card(0), "Replace one -2 card with one +0 card"),
    replace("p02", 2, 1, card(-1), 1, card(1), "Replace one -1 card with one +1 card"),
    replace("p03", 2, 2, card(0), 2, card(0, false, "custom"), "Replace two +0 cards with two +X ★ cards — where X is the poison value of the target"),
    replace("p04", 1, 2, card(1), 2, card(2), "Replace two +1 cards with two +2 cards"),
    replace("p05", 2, 1, card(0), 2, card(0, true, "custom"), "Replace one +0 card with two rolling +0 ★ cards — Create difficult terrain in the hex occupied by the target"),
    replace("p06", 2, 1, card(1), 1, card(0, false, "custom"), "Replace one +1 card with one +0 Wound_x:2 card"),
    add("p07", 1, 4, card(0, true, "custom"), "Add four rolling +0 ★ cards — if the target occupy difficult terrain"),
    add("p08", 1, 2, card(0, true, "invisible"), "Add two rolling +0 Invisible (Self, if you occupy difficult terrain) cards"),
    note("p09", 1, "Gain \"Poison Dagger\" (Item 011). You may carry one additional item with \"Dagger\" in its name"),
    remove("p10", 1, 1, card(-1), "Remove one -1 card — Ignore damage, and negative conditions and modifiers from Events"),
    remove("p11", 1, 1, card(-1), "Remove one -1 card — Ignore negative scenario effects"),
  ],
};
