import type { ClassDef } from "../types";
import { add, card, multi, remove, replace } from "../_perkHelpers";

// Source: github.com/Lurkars/gloomhavensecretariat data/cs/character/skull.json
// Auto-generated by scripts/generate-fan-classes.ts. Custom-perk descriptions
// resolved against GHS's en labels where possible; ★ in card art means the
// effect is fan-expansion specific — see the perk description for the rule.

export const csBombard: ClassDef = {
  id: "cs-bombard",
  game: "crimson-scales",
  name: "Bombard",
  codeName: "Skull",
  iconRef: "skull",
  rulesVariant: "gh",
  startingDeck: "base",
  perks: [
    multi("p01", 1, "Replace one -2 card with one -1 card and one +1 card", { op: "remove", card: card(-2), count: 1 }, { op: "add", card: card(-1), count: 1 }, { op: "add", card: card(1), count: 1 }),
    replace("p02", 2, 1, card(-1), 1, card(0, false, "custom"), "Replace one -1 card with one +0 ★ card — if a Spirit performed the attack"),
    multi("p03", 2, "Replace one -1 card with one +0 card and one rolling +0 Poison card", { op: "remove", card: card(-1), count: 1 }, { op: "add", card: card(0), count: 1 }, { op: "add", card: card(0, true, "poison"), count: 1 }),
    replace("p04", 2, 1, card(0), 1, card(1, false, "air"), "Replace one +0 card with one +1 AIR card"),
    replace("p05", 2, 1, card(0), 1, card(1, false, "dark"), "Replace one +0 card with one +1 DARK card"),
    replace("p06", 1, 1, card(0), 1, card(1, false, "pierce"), "Replace one +0 card with one +1 Pierce 2 card"),
    add("p07", 1, 3, card(0, true, "pierce"), "Add three rolling +0 Pierce 3 cards"),
    add("p08", 1, 1, card(1, false, "curse"), "Add one +1 Curse card"),
    add("p09", 1, 1, card(0, true, "target"), "Add one rolling +0 Target 1 card"),
    replace("p10", 1, 1, card(1), 1, card(2, false, "push"), "Replace one +1 card with one +2 Push 2 card"),
    remove("p11", 1, 1, card(0), "Remove one +0 card — Ignore negative scenario effects"),
  ],
};
