import type { ClassDef } from "../types";
import { add, card, multi, remove, replace } from "../_perkHelpers";

// Source: github.com/Lurkars/gloomhavensecretariat data/cs/character/flask.json
// Auto-generated by scripts/generate-fan-classes.ts. Custom-perk descriptions
// resolved against GHS's en labels where possible; ★ in card art means the
// effect is fan-expansion specific — see the perk description for the rule.

export const csBrightspark: ClassDef = {
  id: "cs-brightspark",
  game: "crimson-scales",
  name: "Brightspark",
  codeName: "Flask",
  iconRef: "flask",
  rulesVariant: "gh",
  startingDeck: "base",
  perks: [
    replace("p01", 3, 1, card(-1), 1, card(0, false, "custom"), "Replace one -1 card with one +0 ★ card — consume WILD"),
    replace("p02", 1, 1, card(-2), 1, card(-2, false, "custom"), "Replace one -2 card with one -2 ★ card"),
    replace("p03", 2, 2, card(0), 1, card(1, false, "heal"), "Replace two +0 cards with one +1 Heal 1 (Affect one ally within Range 2) card"),
    replace("p04", 1, 2, card(0), 1, card(1, false, "shield"), "Replace two +0 cards with one +1 Shield 1 (Affect one ally within Range 2) card"),
    replace("p05", 2, 1, card(1), 1, card(2, false, "wild"), "Replace one +1 card with one +2 WILD card"),
    add("p06", 2, 1, card(1, false, "strengthen"), "Add one +1 Strengthen (Affect one ally within Range 2) card"),
    multi("p07", 1, "Add one rolling +0 ★ AIR card and one rolling +0 Immobilize ICE card", { op: "add", card: card(0, true, "custom", "air"), count: 1 }, { op: "add", card: card(0, true, "immobilize", "ice"), count: 1 }),
    multi("p08", 1, "Add one rolling +0 Heal 1 LIGHT card and one rolling +0 Pierce 2 FIRE card", { op: "add", card: card(0, true, "heal", "light"), count: 1 }, { op: "add", card: card(0, true, "pierce", "fire"), count: 1 }),
    add("p09", 1, 3, card(0, true, "custom"), "Add three rolling +0 ★ cards — consume WILD: WILD"),
    remove("p10", 1, 1, card(-1), "Remove one -1 card — Ignore negative scenario effects"),
  ],
};
