import type { ClassDef } from "../types";
import { add, card, remove, replace } from "../_perkHelpers";

// Source: github.com/Lurkars/gloomhavensecretariat data/cs/character/ladder-axe.json
// Auto-generated by scripts/generate-fan-classes.ts. Custom-perk descriptions
// resolved against GHS's en labels where possible; ★ in card art means the
// effect is fan-expansion specific — see the perk description for the rule.

export const csChieftain: ClassDef = {
  id: "cs-chieftain",
  game: "crimson-scales",
  name: "Chieftain",
  codeName: "Ladder Axe",
  iconRef: "ladder-axe",
  rulesVariant: "gh",
  startingDeck: "base",
  perks: [
    remove("p01", 1, 2, card(-1), "Remove two -1 cards"),
    replace("p02", 2, 1, card(-1), 1, card(0, false, "strengthen"), "Replace one -1 card with one +0 Strengthen (Ally) card"),
    replace("p03", 2, 2, card(0), 1, card(0, false, "custom"), "Replace two +0 cards with one +0 ★ card — if you are on Ladder"),
    replace("p04", 1, 1, card(0), 1, card(1, false, "fire"), "Replace one +0 card with one +1 FIRE card"),
    replace("p05", 1, 1, card(0), 1, card(1, false, "wound"), "Replace one +0 card with one +1 Wound card"),
    replace("p06", 1, 2, card(1), 1, card(2, false, "fire"), "Replace two +1 cards with one +2 FIRE card"),
    replace("p07", 1, 2, card(1), 1, card(2, false, "wound"), "Replace two +1 cards with one +2 Wound card"),
    add("p08", 1, 1, card(1, false, "strengthen"), "Add one +1 Strengthen (Ally) card"),
    add("p09", 2, 2, card(0, true, "heal"), "Add two rolling +0 Heal 1 cards"),
    add("p10", 1, 2, card(0, true, "wound"), "Add two rolling +0 Wound cards"),
    add("p11", 1, 1, card(0, true, "fire"), "Add one rolling +0 FIRE card — Ignore negative item effects"),
    add("p12", 1, 1, card(0, true, "fire"), "Add one rolling +0 FIRE card — Ignore negative scenario effects"),
  ],
};
