import type { ClassDef } from "../types";
import { add, card, remove, replace } from "../_perkHelpers";

// Source: github.com/Lurkars/gloomhavensecretariat data/cs/character/chain-helmet.json
// Auto-generated by scripts/generate-fan-classes.ts. Custom-perk descriptions
// resolved against GHS's en labels where possible; ★ in card art means the
// effect is fan-expansion specific — see the perk description for the rule.

export const csChainguard: ClassDef = {
  id: "cs-chainguard",
  game: "crimson-scales",
  name: "Chainguard",
  codeName: "Chain Helmet",
  iconRef: "chain-helmet",
  rulesVariant: "gh",
  startingDeck: "base",
  perks: [
    replace("p01", 2, 1, card(-1), 1, card(1, false, "custom"), "Replace one -1 card with one +1 ★ card — Shackle"),
    replace("p02", 2, 1, card(-1), 1, card(0, false, "custom"), "Replace one -1 card with one +0 ★ card — transforms to if the target is Shackled"),
    replace("p03", 2, 2, card(0), 1, card(0, true, "shield"), "Replace two +0 cards with one rolling +0 Shield 1 (Self) card"),
    add("p04", 1, 2, card(0, true, "retaliate"), "Add two rolling +0 Retaliate 1 cards"),
    add("p05", 1, 3, card(0, true, "swing"), "Add three rolling +0 Swing 3 cards"),
    replace("p06", 1, 1, card(1), 1, card(2, false, "wound"), "Replace one +1 card with one +2 Wound card"),
    add("p07", 1, 1, card(1, false, "custom"), "Add one +1 ★ card — Disarm if the target is Shackled"),
    add("p08", 1, 1, card(1, false, "custom"), "Add one +1 ★ card — Create a damage 2 trap in an empty hex within Range 2"),
    add("p09", 1, 2, card(0, true, "heal"), "Add two rolling +0 Heal 1 (Self) cards"),
    add("p10", 2, 1, card(2, false, "custom"), "Add one +2 ★ card — Shackle"),
    remove("p11", 1, 1, card(0), "Remove one +0 card — Ignore negative scenario effects"),
  ],
};
