import type { ClassDef } from "../types";
import { add, card, remove, replace } from "../_perkHelpers";

// Source: github.com/Lurkars/gloomhavensecretariat data/cs/character/target.json
// Auto-generated by scripts/generate-fan-classes.ts. Custom-perk descriptions
// resolved against GHS's en labels where possible; ★ in card art means the
// effect is fan-expansion specific — see the perk description for the rule.

export const csFireKnight: ClassDef = {
  id: "cs-fire-knight",
  game: "crimson-scales",
  name: "Fire Knight",
  codeName: "Target",
  iconRef: "target",
  rulesVariant: "gh",
  startingDeck: "base",
  perks: [
    remove("p01", 1, 2, card(-1), "Remove two -1 cards"),
    replace("p02", 1, 2, card(0), 2, card(0, true, "pierce"), "Replace two +0 cards with two rolling +0 Pierce 3 cards"),
    replace("p03", 2, 1, card(-1), 1, card(0, false, "custom"), "Replace one -1 card with one +0 ★ card — transforms to if projectile"),
    add("p04", 2, 1, card(2, false, "immobilize"), "Add one +2 Immobilize card"),
    replace("p05", 1, 1, card(1), 2, card(1, false, "retaliate"), "Replace one +1 card with two +1 Retaliate 1 (range 3) cards"),
    add("p06", 1, 2, card(1, false, "pull"), "Add two +1 Pull 3 cards"),
    add("p07", 1, 1, card(0, false, "strengthen"), "Add one +0 Strengthen (Self) card"),
    add("p08", 1, 1, card(0, false, "stun"), "Add one +0 Stun card"),
    add("p09", 1, 1, card(1, false, "wound"), "Add one +1 Wound card"),
    add("p10", 1, 2, card(0, true, "shield"), "Add two rolling +0 Shield 1 (Self) cards"),
    add("p11", 1, 2, card(0, true, "heal"), "Add two rolling +0 Heal 1 (Self) cards"),
    remove("p12", 1, 1, card(0), "Remove one +0 card — Ignore negative scenario effects"),
    remove("p13", 1, 1, card(0), "Remove one +0 card — Ignore negative item effects"),
  ],
};
