import type { ClassDef } from "../types";
import { add, card, multi, remove, replace } from "../_perkHelpers";

// Source: github.com/Lurkars/gloomhavensecretariat data/cs/character/beetle.json
// Auto-generated by scripts/generate-fan-classes.ts. Custom-perk descriptions
// resolved against GHS's en labels where possible; ★ in card art means the
// effect is fan-expansion specific — see the perk description for the rule.

export const csHierophant: ClassDef = {
  id: "cs-hierophant",
  game: "crimson-scales",
  name: "Hierophant",
  codeName: "Beetle",
  iconRef: "beetle",
  rulesVariant: "gh",
  startingDeck: "base",
  perks: [
    replace("p01", 1, 1, card(-2), 1, card(-1, false, "custom"), "Replace one -2 card with one -1 ★ card — Place one Colony token of your choice on any empty hex within Range 2"),
    remove("p02", 1, 2, card(-1), "Remove two -1 cards"),
    remove("p03", 1, 4, card(0), "Remove four +0 cards"),
    replace("p04", 1, 1, card(-1), 1, card(2, false, "muddle"), "Replace one -1 card with one +2 Muddle card"),
    replace("p05", 1, 1, card(-1), 1, card(1, false, "poison"), "Replace one -1 card with one +1 Poison card"),
    replace("p06", 1, 1, card(-1), 1, card(1, false, "wound"), "Replace one -1 card with one +1 Wound card"),
    add("p07", 2, 2, card(1, true, "immobilize"), "Add two rolling +1 Immobilize cards"),
    multi("p08", 2, "Add one rolling +0 Heal 1 (Self) card and one rolling +0 Shield 1 (Self) card", { op: "add", card: card(0, true, "heal"), count: 1 }, { op: "add", card: card(0, true, "shield"), count: 1 }),
    add("p09", 2, 1, card(0, true, "retaliate"), "Add one rolling +0 Retaliate 1 (range 3) card"),
    add("p10", 1, 1, card(2, false, "earth", "fire"), "Add one +2 EARTH/FIRE (half-element) card"),
    add("p11", 1, 1, card(1), "Add one +1 card — Ignore negative item effects"),
    add("p12", 1, 1, card(0, false, "custom"), "Add one +X ★ card — Ignore negative scenario effects; where X is the number of active Cultivate actions"),
  ],
};
