import type { ClassDef } from "../types";
import { add, card, multi, note, remove, replace } from "../_perkHelpers";

// Source: github.com/Lurkars/gloomhavensecretariat data/cs/character/leaf.json
// Auto-generated by scripts/generate-fan-classes.ts. Custom-perk descriptions
// resolved against GHS's en labels where possible; ★ in card art means the
// effect is fan-expansion specific — see the perk description for the rule.

export const csHollowpact: ClassDef = {
  id: "cs-hollowpact",
  game: "crimson-scales",
  name: "Hollowpact",
  codeName: "Leaf",
  iconRef: "leaf",
  rulesVariant: "gh",
  startingDeck: "base",
  perks: [
    remove("p01", 1, 1, card(-1), "Remove one -1 card"),
    replace("p02", 1, 2, card(0), 1, card(0, true, "light"), "Replace two +0 cards with one rolling +0 LIGHT card"),
    replace("p03", 1, 2, card(0), 1, card(0, true, "earth"), "Replace two +0 cards with one rolling +0 EARTH card"),
    replace("p04", 2, 1, card(-1), 1, card(0, false, "curse"), "Replace one -1 card with one +0 Curse card"),
    replace("p05", 1, 1, card(0), 1, card(1, false, "shield"), "Replace one +0 card with one +1 Shield 1 (Ally) card"),
    multi("p06", 1, "Replace one -2 card with one -1 ★ card and one +0 card — Give one ally a `Prayer´ ability", { op: "remove", card: card(-2), count: 1 }, { op: "add", card: card(-1, false, "custom"), count: 1 }, { op: "add", card: card(0), count: 1 }),
    replace("p07", 2, 1, card(1), 1, card(3), "Replace one +1 card with one +3 card"),
    add("p08", 2, 2, card(0, true, "heal"), "Add two rolling +0 Heal 1 (Self or ally) cards"),
    add("p09", 2, 1, card(1, false, "wound", "muddle"), "Add one +1 Wound Muddle card"),
    note("p10", 1, "At the start of your first turn each scenario, gain Bless"),
    remove("p11", 1, 1, card(0), "Remove one +0 card — Ignore negative scenario effects"),
  ],
};
