import type { ClassDef } from "../types";
import { add, card, remove, replace } from "../_perkHelpers";

// Source: github.com/Lurkars/gloomhavensecretariat data/cs/character/crescent-sun.json
// Auto-generated by scripts/generate-fan-classes.ts. Custom-perk descriptions
// resolved against GHS's en labels where possible; ★ in card art means the
// effect is fan-expansion specific — see the perk description for the rule.

export const csLuminary: ClassDef = {
  id: "cs-luminary",
  game: "crimson-scales",
  name: "Luminary",
  codeName: "Crescent Sun",
  iconRef: "crescent-sun",
  rulesVariant: "gh",
  startingDeck: "base",
  perks: [
    remove("p01", 1, 4, card(0), "Remove four +0 cards"),
    replace("p02", 1, 1, card(0), 1, card(2), "Replace one +0 card with one +2 card"),
    replace("p03", 1, 1, card(-1), 1, card(0, false, "ice"), "Replace one -1 card with one +0 ICE card"),
    replace("p04", 1, 1, card(-1), 1, card(0, false, "fire"), "Replace one -1 card with one +0 FIRE card"),
    replace("p05", 1, 1, card(-1), 1, card(0, false, "light"), "Replace one -1 card with one +0 LIGHT card"),
    replace("p06", 1, 1, card(-1), 1, card(0, false, "dark"), "Replace one -1 card with one +0 DARK card"),
    replace("p07", 1, 1, card(-2), 1, card(-2, false, "custom"), "Replace one -2 card with one -2 ★ card — Perform one Glow ability"),
    add("p08", 2, 1, card(0, false, "wild"), "Add one +0 WILD card"),
    add("p09", 2, 2, card(1, true, "heal"), "Add two rolling +1 Heal 1 (Self) cards"),
    add("p10", 2, 1, card(0, false, "poison"), "Add one +0 Poison card"),
    remove("p11", 1, 1, card(0), "Remove one +0 card — Ignore negative scenario effects"),
    add("p12", 1, 1, card(0, true, "custom"), "Add one rolling +0 ★ card — Ignore negative item effects; consume WILD: WILD"),
  ],
};
