import type { ClassDef } from "../types";
import { card, replace } from "../_perkHelpers";

// Source: github.com/Lurkars/gloomhavensecretariat data/cs/character/tools.json
// Auto-generated by scripts/generate-fan-classes.ts. Custom-perk descriptions
// resolved against GHS's en labels where possible; ★ in card art means the
// effect is fan-expansion specific — see the perk description for the rule.

export const csMirefoot: ClassDef = {
  id: "cs-mirefoot",
  game: "crimson-scales",
  name: "Mirefoot",
  codeName: "Tools",
  iconRef: "tools",
  rulesVariant: "gh",
  startingDeck: "base",
  perks: [
    replace("p01", 1, 1, card(-2), 1, card(-1, false, "wild"), "Replace one -2 card with one -1 WILD card"),
    replace("p02", 1, 1, card(-1), 1, card(1, false, "disarm"), "Replace one -1 card with one +1 Disarm card"),
    replace("p03", 2, 1, card(-1), 1, card(1, false, "push"), "Replace one -1 card with one +1 Push 1 card"),
    replace("p04", 2, 1, card(-1), 1, card(1, false, "pull"), "Replace one -1 card with one +1 Pull 1 card"),
    replace("p05", 2, 1, card(0), 1, card(0, false, "custom"), "Replace one +0 card with one +0 ★ card"),
    replace("p06", 2, 1, card(0), 1, card(1, false, "shield"), "Replace one +0 card with one +1 Shield 1 (Self) card"),
    replace("p07", 2, 1, card(0), 1, card(1, false, "pierce"), "Replace one +0 card with one +1 Pierce 2 card"),
    replace("p08", 1, 1, card(2), 1, card(3, false, "heal"), "Replace one +2 card with one +3 Heal 2 (Self) card"),
    replace("p09", 1, 2, card(1), 2, card(1, true, "poison"), "Replace two +1 cards with two rolling +1 Poison cards"),
    replace("p10", 1, 2, card(1), 2, card(1, true, "wound"), "Replace two +1 cards with two rolling +1 Wound cards"),
  ],
};
