import type { ClassDef } from "../types";
import { add, card, replace } from "../_perkHelpers";

// Source: github.com/Lurkars/gloomhavensecretariat data/cs/character/tusks.json
// Auto-generated by scripts/generate-fan-classes.ts. Custom-perk descriptions
// resolved against GHS's en labels where possible; ★ in card art means the
// effect is fan-expansion specific — see the perk description for the rule.

export const csRuinmaw: ClassDef = {
  id: "cs-ruinmaw",
  game: "crimson-scales",
  name: "Ruinmaw",
  codeName: "Tusks",
  iconRef: "tusks",
  rulesVariant: "gh",
  startingDeck: "base",
  perks: [
    replace("p01", 1, 1, card(-1), 1, card(0, false, "poison"), "Replace one -1 card with one +0 Poison card"),
    replace("p02", 2, 1, card(-1), 1, card(0, false, "heal"), "Replace one -1 card with one +0 Heal 1 card"),
    replace("p03", 2, 1, card(-1), 1, card(0, false, "heal"), "Replace one -1 card with one +0 Heal 1 (Affect all summoned allies owned) card"),
    replace("p04", 1, 1, card(-2), 1, card(-2, false, "bless"), "Replace one -2 card with one -2 Bless (Self) card"),
    replace("p05", 1, 2, card(0), 1, card(0, false, "immobilize", "push"), "Replace two +0 cards with one +0 Immobilize Push 1 card"),
    replace("p06", 2, 1, card(0), 1, card(0, false, "custom"), "Replace one +0 card with one +X ★ card — where X is the number of summoned allies you own"),
    replace("p07", 1, 1, card(1), 2, card(1, true, "custom"), "Replace one +1 card with two rolling +1 ★ cards — if summon is attacking"),
    add("p08", 1, 1, card(0, false, "wound", "pierce"), "Add one +0 Wound Pierce 1 card"),
    add("p09", 2, 1, card(1, false, "earth"), "Add one +1 EARTH card"),
    add("p10", 1, 2, card(0, true, "pierce", "custom"), "Add two rolling +0 Pierce 2 ★ cards — ignore Retaliate on the target"),
    add("p11", 1, 1, card(1), "Add one +1 card — Ignore negative scenario effects"),
  ],
};
