import type { ClassDef } from "../types";
import { add, card, remove, replace } from "../_perkHelpers";

// Source: github.com/Lurkars/gloomhavensecretariat data/cs/character/galaxy.json
// Auto-generated by scripts/generate-fan-classes.ts. Custom-perk descriptions
// resolved against GHS's en labels where possible; ★ in card art means the
// effect is fan-expansion specific — see the perk description for the rule.

export const csStarslinger: ClassDef = {
  id: "cs-starslinger",
  game: "crimson-scales",
  name: "Starslinger",
  codeName: "Galaxy",
  iconRef: "galaxy",
  rulesVariant: "gh",
  startingDeck: "base",
  perks: [
    replace("p01", 2, 2, card(0), 1, card(0, true, "heal"), "Replace two +0 cards with one rolling +0 Heal 1 (Self) card"),
    replace("p02", 1, 1, card(-2), 1, card(-1, false, "invisible"), "Replace one -2 card with one -1 Invisible (Self) card"),
    replace("p03", 1, 2, card(-1), 1, card(0, false, "dark"), "Replace two -1 cards with one +0 DARK card"),
    replace("p04", 2, 1, card(-1), 1, card(0, false, "light"), "Replace one -1 card with one +0 LIGHT card"),
    add("p05", 1, 1, card(0, true, "custom"), "Add one rolling +0 ★ card"),
    add("p06", 2, 1, card(1, false, "custom"), "Add one +1 ★ card — if you are at full health"),
    add("p07", 1, 2, card(0, true, "immobilize"), "Add two rolling +0 Immobilize cards"),
    add("p08", 2, 1, card(1, false, "heal"), "Add one +1 Heal 1 card"),
    add("p09", 1, 2, card(0, true, "custom"), "Add two rolling +0 ★ cards — Force the target to perform ´Move 1´"),
    add("p10", 1, 2, card(0, true, "heal"), "Add two rolling +0 Heal 1 cards"),
    remove("p11", 1, 1, card(0), "Remove one +0 card — Ignore negative scenario effects"),
  ],
};
