import type { ClassDef } from "../types";
import { card, note, remove, replace } from "../_perkHelpers";

// Source: github.com/Lurkars/gloomhavensecretariat data/cs/character/bleeding-claw.json
// Auto-generated by scripts/generate-fan-classes.ts. Custom-perk descriptions
// resolved against GHS's en labels where possible; ★ in card art means the
// effect is fan-expansion specific — see the perk description for the rule.

export const csSpiritCaller: ClassDef = {
  id: "cs-spirit-caller",
  game: "crimson-scales",
  name: "Spirit Caller",
  codeName: "Bleeding Claw",
  iconRef: "bleeding-claw",
  rulesVariant: "gh",
  startingDeck: "base",
  perks: [
    replace("p01", 1, 1, card(-2), 1, card(-1, false, "custom", "wound"), "Replace one -2 card with one -1 Rupture Wound card"),
    replace("p02", 2, 1, card(-1), 1, card(0, false, "wound"), "Replace one -1 card with one +0 Wound card"),
    replace("p03", 2, 1, card(-1), 1, card(0, false, "custom"), "Replace one -1 card with one +0 Rupture card"),
    replace("p04", 3, 1, card(0), 1, card(1, false, "custom"), "Replace one +0 card with one +1 ★ card — transforms to if the target has Rupture or Wound"),
    replace("p05", 3, 1, card(0), 1, card(0, true, "heal", "custom"), "Replace one +0 card with one rolling +0 Heal 1 (Self) Empower card"),
    note("p06", 1, "Once each scenario, become after collecting your fifth loot token"),
    note("p07", 1, "Become each time you lose a card to negate suffering damage"),
    note("p08", 1, "Whenever one of your abilities causes at least one enemy to gain Rupture, immediately after that ability perform \"Move 1\""),
    remove("p09", 1, 1, card(-1), "Remove one -1 card — Ignore negative scenario effects"),
  ],
};
